stages:
    - docker
    - singularity
    - clean

variables:
    OUTDIR: "/scratch/gitlab-runner/${CI_PROJECT_PATH}/${CI_COMMIT_SHA}"

docker:
    stage: docker
    tags: [docker]
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script:
        - mkdir -p /kaniko/.docker
        - mkdir -p ${OUTDIR}
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$CI_DEPENDENCY_PROXY_SERVER\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --no-push --tarPath="${OUTDIR}/image.tar" --destination=image

singularity:
    stage: singularity
    tags: [docker]
    image:
        name: quay.io/singularity/singularity:3.10.2
        entrypoint: [""]
    script:
        - singularity build "${OUTDIR}/image.sif" "${OUTDIR}/image.tar"

install:
    stage: install
    tags: [gadi]
    script:
        - scp gitlab-runner:${OUTDIR}/image.sif .

clean:
    stage: clean
    tags: [docker]
    script: rm -rv "${OUTDIR}"
    when: always
