build:
    stage: build
    tags: [docker]
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script:
        - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
