stages:
    - build
    - install staging
    - install production
    - clean

variables:
    # SETUP: Set a different module name if desired
    NAME: "$CI_PROJECT_NAME"
    VERSION: "$CI_COMMIT_REF_NAME"

create image:
    stage: build
    tags: [gadi]
    script:
        - submit.sh
