#!/bin/bash

# Runs a command in the container

SCRIPT_DIR=$( cd -- "$( dirname -- "$(readlink -f ${BASH_SOURCE[0]})" )" &> /dev/null && pwd )

export SINGULARITYENV_APPEND_PATH=$PATH
export SINGULARITYENV_LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib64:/lib:/half-root/lib64:/half-root/lib
export SINGULARITY_BIND=/half-root,/opt/pbs,/etc/pbs.conf,/var/run/munge

CMD=$(basename $0)

if [ "$CMD" != "imagerun" ]; then
    ARGS=("$CMD" "$@")
else
    ARGS=("$@")

    if [ "$1" == "shell" ]; then
        /opt/singularity/bin/singularity shell ${SCRIPT_DIR}/../etc/image.sif
        exit "$?"
    fi
fi

/opt/singularity/bin/singularity run ${SCRIPT_DIR}/../etc/image.sif "${ARGS[@]}"
